QA-1595: Terraform resources for TestRunner Dashboard.
broadinstitute/terraform-ap-modules pull request #206
Opened 2021-10-06 00:21 UTC by ichengchang

This PR consists of additional Terraform resources for `TestRunner Dashboard`.

2021-10-15 17:00 UTC, jack-r-warren approved these changes
This looks good--maybe we hold off to merge until we've tested in https://github.com/broadinstitute/terraform-ap-deployments/pull/434

2021-10-15 17:00 UTC, jack-r-warren commented on testrunner/provider.tf
> +}
```suggestion
}

```
nit

2021-10-19 14:06 UTC, ichengchang commented on testrunner/provider.tf
> +}
Fixed.

2021-11-02 15:10 UTC, ichengchang commented
@jack-r-warren Could you review this ticket again? Just a few changes.

Updated all tf resources with `enable` or `enable_dashboard`. 
We can just turn off `enable_dashboard` for environments that don't need dashboard resources, or vice versa.

2021-11-02 15:46 UTC, jack-r-warren requested changes
Three high-level things:
- When we talked on Friday Ambica was clear that preview environments were out of scope for this iteration of the project. Let's remove all references to preview environments--and frankly environment types altogether--here, since what's here is incompatible with how preview environments work. 
- There's a lot of instances here of using `count`/`element` to make multiple of a resource. Let's use `for_each` like we talked about, since it is designed for this purpose and produces better error messages if something goes wrong.
- The way you've got this set up now, you'll need multiple tfvars files for a single deployment--one with the dashboard enabled and the rest with it disabled to do permissions. A tfvars file should correspond to a single deployment of an app or service. Like we talked about, you can use submodules or for_each to set config in multiple projects from a single Terraform workspace (that is, from a single tfvars file). Let's do that to keep testrunner in line with our other Terraform patterns. (The multiple tfvars files are in https://github.com/broadinstitute/terraform-ap-deployments/pull/434/files but we don't care where you do the iteration there or here)

2021-11-04 14:05 UTC, jack-r-warren approved these changes
Approving to unblock

2021-11-08 21:36 UTC, merged